export function buildTools() {
  const scoreInt = { type: "integer", minimum: 0, maximum: 3 };
  const evidenceStrength = {
    type: "string",
    enum: ["explicit_verified", "credible_indirect", "vague_rep_assertion", "unknown_missing"],
  };
  const confidence = {
    type: "string",
    enum: ["high", "medium", "low"],
  };
  return [
    {
      type: "function",
      name: "save_deal_data",
      description:
        "REQUIRED after EVERY rep answer. Save the score (0-3), summary, and coaching tip for the category you just asked about. When the category is Champion/Internal Sponsor or Economic Buyer, include champion_name, champion_title, eb_name, eb_title when the rep has stated them.",
      parameters: {
        type: "object",
        properties: {
          pain_score: scoreInt,
          pain_summary: { type: "string" },
          pain_tip: { type: "string" },
          pain_evidence_strength: evidenceStrength,
          pain_confidence: confidence,
          metrics_score: scoreInt,
          metrics_summary: { type: "string" },
          metrics_tip: { type: "string" },
          metrics_evidence_strength: evidenceStrength,
          metrics_confidence: confidence,
          champion_score: scoreInt,
          champion_summary: { type: "string" },
          champion_tip: { type: "string" },
          champion_evidence_strength: evidenceStrength,
          champion_confidence: confidence,
          champion_name: { type: "string" },
          champion_title: { type: "string" },
          eb_score: scoreInt,
          eb_summary: { type: "string" },
          eb_tip: { type: "string" },
          eb_evidence_strength: evidenceStrength,
          eb_confidence: confidence,
          eb_name: { type: "string" },
          eb_title: { type: "string" },
          criteria_score: scoreInt,
          criteria_summary: { type: "string" },
          criteria_tip: { type: "string" },
          criteria_evidence_strength: evidenceStrength,
          criteria_confidence: confidence,
          process_score: scoreInt,
          process_summary: { type: "string" },
          process_tip: { type: "string" },
          process_evidence_strength: evidenceStrength,
          process_confidence: confidence,
          competition_score: scoreInt,
          competition_summary: { type: "string" },
          competition_tip: { type: "string" },
          competition_evidence_strength: evidenceStrength,
          competition_confidence: confidence,
          paper_score: scoreInt,
          paper_summary: { type: "string" },
          paper_tip: { type: "string" },
          paper_evidence_strength: evidenceStrength,
          paper_confidence: confidence,
          timing_score: scoreInt,
          timing_summary: { type: "string" },
          timing_tip: { type: "string" },
          timing_evidence_strength: evidenceStrength,
          timing_confidence: confidence,
          budget_score: scoreInt,
          budget_summary: { type: "string" },
          budget_tip: { type: "string" },
          budget_evidence_strength: evidenceStrength,
          budget_confidence: confidence,
          risk_summary: { type: "string" },
          next_steps: { type: "string" },
          rep_comments: { type: "string" },
          entity_override: { type: "boolean", description: "If the rep gives a new name and/or title for EB or Champion, accept it. They can change it back if it is wrong." },
        },
        required: [],
      },
      // Keep non-strict to match current behavior (optional fields).
      strict: false,
    },
    {
      type: "function",
      name: "advance_deal",
      description: "Advance to the next deal after end-of-deal wrap.",
      parameters: { type: "object", properties: {} },
      strict: false,
    },
  ];
}

