CREATE TABLE IF NOT EXISTS ai_takeaway_cache (
  id integer GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
  org_id integer NOT NULL
    REFERENCES organizations(id) ON DELETE CASCADE,
  surface text NOT NULL,
  payload_sha text NOT NULL,
  summary text NOT NULL,
  extended text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (org_id, surface, payload_sha)
);

CREATE INDEX IF NOT EXISTS
  idx_ai_takeaway_cache_lookup
  ON ai_takeaway_cache (org_id, surface, payload_sha);
