-- Extend multi-tenant schema:
-- - organizations: profile fields + parent org relationship
-- - users: hierarchy_level + admin_has_full_analytics_access
-- - email_templates: SaaS-owner managed templates (stub)

-- ----------------------------
-- organizations: profile fields
-- ----------------------------
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS parent_org_id integer;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS billing_plan text;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS hq_address_line1 text;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS hq_address_line2 text;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS hq_city text;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS hq_state text;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS hq_postal_code text;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS hq_country text;

-- Optional: FK for parent_org_id.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
      FROM pg_constraint
     WHERE conname = 'organizations_parent_org_id_fkey'
  ) THEN
    ALTER TABLE organizations
      ADD CONSTRAINT organizations_parent_org_id_fkey
      FOREIGN KEY (parent_org_id) REFERENCES organizations(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS organizations_parent_org_id_idx ON organizations(parent_org_id);

-- ----------------------------
-- users: hierarchy + analytics access flags
-- ----------------------------
ALTER TABLE users ADD COLUMN IF NOT EXISTS hierarchy_level integer;
ALTER TABLE users ADD COLUMN IF NOT EXISTS admin_has_full_analytics_access boolean;

UPDATE users
   SET hierarchy_level = COALESCE(hierarchy_level, CASE WHEN role = 'REP' THEN 0 WHEN role = 'MANAGER' THEN 1 ELSE 0 END)
 WHERE hierarchy_level IS NULL;

UPDATE users
   SET admin_has_full_analytics_access = COALESCE(admin_has_full_analytics_access, false)
 WHERE admin_has_full_analytics_access IS NULL;

ALTER TABLE users ALTER COLUMN hierarchy_level SET DEFAULT 0;
ALTER TABLE users ALTER COLUMN admin_has_full_analytics_access SET DEFAULT false;

-- If you want strict NOT NULLs, uncomment after backfill is complete in all environments:
-- ALTER TABLE users ALTER COLUMN hierarchy_level SET NOT NULL;
-- ALTER TABLE users ALTER COLUMN admin_has_full_analytics_access SET NOT NULL;

CREATE INDEX IF NOT EXISTS users_org_manager_user_id_idx ON users(org_id, manager_user_id);
CREATE INDEX IF NOT EXISTS users_org_role_idx ON users(org_id, role);

-- ----------------------------
-- email_templates (global)
-- ----------------------------
CREATE TABLE IF NOT EXISTS email_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_key text NOT NULL,
  subject text NOT NULL,
  body text NOT NULL,
  active boolean NOT NULL DEFAULT TRUE,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS email_templates_key_uq ON email_templates(template_key);

-- Seed placeholder templates (best-effort).
INSERT INTO email_templates (template_key, subject, body, active, created_at, updated_at)
VALUES
  ('welcome', 'Welcome to Forecast Agent', 'Welcome {{display_name}} to {{org_name}}.', TRUE, NOW(), NOW()),
  ('invite', 'You''re invited to Forecast Agent', 'Hi {{display_name}}, set your password: {{invite_link}}', TRUE, NOW(), NOW()),
  ('reset', 'Reset your Forecast Agent password', 'Reset your password: {{reset_link}}', TRUE, NOW(), NOW())
ON CONFLICT (template_key) DO NOTHING;

