export type HubSpotDealState = {
  account_name: string | null;
  opportunity_name: string | null;
  forecast_stage: string | null;
  amount: number | null;
  close_date: string | null;
  rep_name: string | null;
  partner_name: string | null;
  champion_name: string | null;
  champion_title: string | null;
  eb_name: string | null;
  eb_title: string | null;
  risk_summary: string | null;
  next_steps: string | null;
  health_score: number | null;
  health_pct: number | null;
  confidence_band: string | null;
  ai_verdict: string | null;
  pain_score: number | null;
  metrics_score: number | null;
  champion_score: number | null;
  eb_score: number | null;
  criteria_score: number | null;
  process_score: number | null;
  competition_score: number | null;
  paper_score: number | null;
  timing_score: number | null;
  budget_score: number | null;
  pain_summary: string | null;
  metrics_summary: string | null;
  champion_summary: string | null;
  eb_summary: string | null;
  criteria_summary: string | null;
  process_summary: string | null;
  competition_summary: string | null;
  paper_summary: string | null;
  timing_summary: string | null;
  budget_summary: string | null;
  pain_tip: string | null;
  metrics_tip: string | null;
  champion_tip: string | null;
  eb_tip: string | null;
  criteria_tip: string | null;
  process_tip: string | null;
  competition_tip: string | null;
  paper_tip: string | null;
  timing_tip: string | null;
  budget_tip: string | null;
};

export type HubSpotReviewSession = {
  org_id: number;
  rep_id: number;
  opportunity_id: number;
  public_id: string;
  crm_opp_id: string;
  dealState: HubSpotDealState;
};

